server:
  port: "8080"

database:
  host: "localhost"
  port: "3306"
  user: "root"
  password: "wyb"
  name: "ai_cloud"

jwt:
  secret: "wyb010607"
  expiration_hours: 24

storage:
  type: "local" # 或 oss
  local:
    base_dir: "./storage_data"
  oss:
    endpoint: "oss-cn-nanjing.aliyuncs.com"
    bucket: "smkl-obsidian"
    access_key_id: ""
    access_key_secret: ""

# 新增 CORS 配置
cors:
  allow_origins:
    - "*"
  allow_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "PATCH"
    - "DELETE"
    - "OPTIONS"
  allow_headers:
    - "Origin"
    - "Content-Type"
    - "Accept"
    - "Authorization"
  expose_headers:
    - "Content-Length"
  allow_credentials: true
  max_age: "12h" # 12 小时